# online configuration valid between the dates of Apr 24, 2024 and Nov 05, 2024

io:
  # Input HFET hd5 files, one file per fill
  input_dir: "/eos/cms/store/group/dpg_bril/comm_bril/2024/physics"
  #input_dir: "/cephfs/brilshare/leeja/hf_reprocessed/hfoc/24_uncorr"
  beam_dir:  "/eos/cms/store/group/dpg_bril/comm_bril/2024/physics"
  input_pattern: "{fill}/{fill}_*.hd5"
  #input_pattern: "{fill}/{fill}.hd5"

  # Output files, to avoid overwriting the old version
  output_dir: "/cephfs/brilshare/leeja/hf_reprocessed/hfoc/24"
  output_pattern: "{fill}/{fill}.hd5"

  # HDF5 node / key with the HF table
  node: "hfoclumi"

  # Precomputed active BX mask (shape=(3564,), dtype=int)
  # Can be produced once from the beam hd5
  active_mask_pattern: "/cephfs/brilshare/alshevel/hf_masks/activeBXMask_fill{fill}.npy"

  # Directory where Type-1 diagnostic plots (etc.) are stored
  type1_dir: "/eos/user/l/leeja/HF/plots_hfpipe/OC/24"

steps:
  online_recovery: true
  restore_rates:   true
  compute_type1:   true
  apply_type1:     true
  bunch_train:     true

online_recovery:
  method: "online" # can be either "tables" or "online"

  # for tables recovery
  afterglow_node: null

  # for online recovery
  hfsbr_pattern: "/home/leeja/hfpipe/input/afterglow/hfoc_online_Apr24_24.txt"

  # online type 1
  # these were in effect from Apr 24, 2024 to Nov 05, 2024
  linear_type1: [0.00115058, 9.62720752e-05, -2.38976234e-05]
  quad_type1: [0.00118399, 9.97966854e-05, 7.25134025e-05]

  # online pedestal
  # set to null if there is no online pedestal
  pedestal_node: null

afterglow:

  # BX indices to hard-clean (mu_true = 0) – analogue of BX_TO_CLEAN
  bx_to_clean: [3488, 3489, 3490, 3491, 3553, 3554, 3555, 3556, 3557]
  
  hfsbr_pattern: "/home/leeja/hfpipe/input/afterglow/hfoc_10843.txt"
  #hfsbr_pattern: "/home/leeja/hfpipe/input/afterglow/hfoc_online_Apr24_24.txt"
  
  # Regularization strengths for the LSQ inversion
  lambda_reg: 0.01
  lambda_nonactive: 0.05
  
  n_jobs: 16

  # Conversion example: bx = bxraw * 11245.6 / sigvis
  sigvis: 931.3

type1:
  # Offsets (in BX) between the main bunch and the tail to be fitted
  offsets: [1, 2, 3, 4]

  # Minimum SBIL for including a point in the Type-1 fit
  sbil_min: 0.1

  # Whether to produce Type-1 summary plots
  make_plots: true

  debug: true             # draw "before" Type-1 plots directly in compute_type1_step
  debug_after_apply: true # draw "after" Type-1 plots in apply_type1_step

  # Do not store heavy intermediate type1_{offset}.h5 files
  save_hd5: false

bunch_train:
  # location of data to use as a linear reference for the bunch train effect
  linear_reference: "/cephfs/brilshare/alshevel/hf_reprocessed/hfet/24_final/"
  input_pattern: "{fill}/{fill}_*.hd5"
  node: "hfetlumi"
  #linear_reference: "/eos/cms/store/group/dpg_bril/comm_bril/2025/physics"
  #input_pattern: "{fill}/{fill}_*.hd5"
  #node: "bcm1futcalumi"

  # order of the poly fit to apply
  order: 3
  
  # Minimum SBIL for including a point in the fit
  sbil_min: 0.1

  make_plots: True
  save_hd5: False

fills:
 - 9575
 - 9659
 - 9661
 - 9663
 - 9691
 - 9832
 - 9838
 - 9840
 - 9842
 - 9843
 - 9846
 - 9848
 - 9849
 - 9851
 - 9852
 - 9857
 - 9859
 - 9860
 - 9861
 - 9862
 - 9864
 - 9865
 - 9867
 - 9869
 - 9871
 - 9873
 - 9877
 - 9878
 - 9879
 - 9883
 - 9885
 - 9886
 - 9891
 - 9895
 - 9896
 - 9899
 - 9900
 - 9904
 - 9905
 - 9906
 - 9910
 - 9911
 - 9912
 - 9917
 - 9920
 - 9921
 - 9923
 - 9925
 - 9926
 - 9927
 - 9931
 - 9932
 - 9934
 - 9935
 - 9936
 - 9937
 - 9939
 - 9941
 - 9942
 - 9943
 - 9945
 - 9947
 - 9951
 - 9960
 - 9962
 - 9966
 - 9967
 - 9969
 - 9970
 - 9971
 - 9973
 - 9974
 - 9978
 - 9982
 - 9983
 - 9984
 - 9986
 - 9987
 - 9988
 - 9989
 - 9992
 - 9994
 - 9995
 - 9996
 - 10000
 - 10001
 - 10002
 - 10004
 - 10005
 - 10006
 - 10010
 - 10012
 - 10013
 - 10014
 - 10016
 - 10017
 - 10049
 - 10050
 - 10052
 - 10056
 - 10059
 - 10061
 - 10066
 - 10068
 - 10069
 - 10070
 - 10072
 - 10073
 - 10074
 - 10075
 - 10077
 - 10082
 - 10084
 - 10086
 - 10087
 - 10090
 - 10091
 - 10092
 - 10093
 - 10094
 - 10095
 - 10096
 - 10097
 - 10098
 - 10099
 - 10100
 - 10102
 - 10104
 - 10105
 - 10107
 - 10109
 - 10112
 - 10115
 - 10116
 - 10117
 - 10118
 - 10119
 - 10122
 - 10123
 - 10125
 - 10126
 - 10127
 - 10130
 - 10132
 - 10134
 - 10137
 - 10138
 - 10139
 - 10141
 - 10142
 - 10143
 - 10144
 - 10189
 - 10190
 - 10197
 - 10199
 - 10200
 - 10201
 - 10202
 - 10204
 - 10206
 - 10207
 - 10208
 - 10209
 - 10210
 - 10211
 - 10213
 - 10214
 - 10215
 - 10216
 - 10218
 - 10219
 - 10222
 - 10223
 - 10226
 - 10230
 - 10232
 - 10296
 - 10297
 - 10298
 - 10299
 - 10301
 - 10302
 - 10304
 - 10305
 - 10307
 - 10309
 - 10310
 - 10311
 - 10312
